#Distance at which the probe works
#Range: 0.1 ~ 200.0
probeDistance = 9.0
#The distance to the left side of the screen. Use -1 if you don't want to set this
#Range: -1 ~ 10000
boxLeftX = -1
#The distance to the right side of the screen. Use -1 if you don't want to set this
#Range: -1 ~ 10000
boxRightX = -1
#The distance to the top side of the screen. Use -1 if you don't want to set this
#Range: -1 ~ 10000
boxTopY = 5
#The distance to the bottom side of the screen. Use -1 if you don't want to set this
#Range: -1 ~ 10000
boxBottomY = -1
#Color of the border of the box (0 to disable)
boxBorderColor = "0"
#Color of the box (0 to disable)
boxFillColor = "0"
#Thickness of the border of the box (0 to disable)
#Range: 0 ~ 20
boxThickness = 0
#How much the border should be offset (i.e. to create an 'outer' border)
#Range: 0 ~ 20
boxOffset = 0
#Toggle default probe visibility (client can override)
isVisible = true
#The scale of the tooltips, 1 is default, 2 is smaller
#Range: 0.4 ~ 5.0
tooltipScale = 1.0

