#Settings for all things related to the uncrafting table.
["Uncrafting Table"]
	#Disable the uncrafting function of the uncrafting table. Recommended as a last resort if there's too many things to change about its behavior.
	disableUncrafting = true

